# Generated by Django 4.2.13 on 2024-05-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='option',
            field=models.CharField(default='basic_option', max_length=100),
            preserve_default=False,
        ),
    ]
