# Generated by Django 4.2.13 on 2024-05-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_variant_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='option',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='product',
            name='variants',
            field=models.ManyToManyField(blank=True, to='product.variant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
